FROM ubuntu:17.10

EXPOSE 8080

COPY requirements.txt /data/requirements.txt

RUN apt-get update && \
    apt-get install --no-install-recommends -y -q \
		    apt-utils \
		    build-essential \
		    python3 \
		    python3-setuptools \
		    python3-pip && \
    pip3 install wheel && \
    pip3 install -r /data/requirements.txt
